/*
 * Copyright (c) 2022, Arm Limited and affiliates.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*********************    Autogenerated file. DO NOT EDIT *******************
 * Generated from gen_labels_cpp.py tool and labels_mobilenet_v2_1.0_224.txt file.
 * Date: 2022-04-11 11:48:51.860892
 ***************************************************************************/

#include "BufAttributes.hpp"

#include <vector>
#include <string>


//static const char *labelsVec_CNNH[] LABELS_ATTRIBUTE =
//{
//    "Live Face",
//    "Print Attack",
//    "Replay Attack"
//};

//static const char *labelsVec_MN3S[] LABELS_ATTRIBUTE =
//{
//    "Live Face",
//    "Fake Attack"
//};

bool GetLabelsVector(std::vector<std::string> &labels, const char *labelsVec[], size_t labelsSz)
{

    //constexpr size_t labelsSz = 3;

    labels.clear();

    if (!labelsSz)
    {
        return false;
    }

    labels.reserve(labelsSz);

    for (size_t i = 0; i < labelsSz; ++i)
    {
        labels.emplace_back(labelsVec[i]);
    }

    return true;
}

