/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by torchgen/gen_executorch.py
// Exposing an API for registering all kernels at once.
#include <executorch/runtime/core/error.h>
#include <executorch/runtime/core/evalue.h>
#include <executorch/runtime/core/exec_aten/exec_aten.h>
#include <executorch/runtime/kernel/operator_registry.h>
#include <executorch/runtime/platform/profiler.h>

using executorch::runtime::Error;

namespace executorch {
namespace backends {
namespace arm {

Error register_ethosu_backend();

} // namespace arm
} // namespace backends
} // namespace executorch
